spring.datasource.url=jdbc:mysql://localhost:3306/trendyvibe
spring.datasource.username=root
spring.datasource.password=roshni

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=trendyvibe-secret-key-2024-rose-erode
jwt.expiration=86400000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=roshniabisri@gmail.com
spring.mail.password=edhyuwqqwuyuyggq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.admin.email=admin@trendyvibe.com
app.admin.password=admin123
